Ошибка: HTTPConnectionPool(host='11', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB1A2F0>: Failed to resolve '11' ([Errno 11001] getaddrinfo failed)"))