Ошибка: HTTPConnectionPool(host='114', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020276543AC0>: Failed to resolve '114' ([Errno 11001] getaddrinfo failed)"))