Ошибка: HTTPConnectionPool(host='116', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AAE5F00>: Failed to resolve '116' ([Errno 11001] getaddrinfo failed)"))