Ошибка: HTTPConnectionPool(host='118', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AAE6A10>: Failed to resolve '118' ([Errno 11001] getaddrinfo failed)"))