Ошибка: HTTPConnectionPool(host='119', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AAE5DB0>: Failed to resolve '119' ([Errno 11001] getaddrinfo failed)"))