Ошибка: HTTPConnectionPool(host='136', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB4A3B0>: Failed to resolve '136' ([Errno 11001] getaddrinfo failed)"))