Ошибка: HTTPConnectionPool(host='138', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AAE72B0>: Failed to resolve '138' ([Errno 11001] getaddrinfo failed)"))