Ошибка: HTTPConnectionPool(host='31', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027ABC50C0>: Failed to resolve '31' ([Errno 11001] getaddrinfo failed)"))