Ошибка: HTTPConnectionPool(host='36', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB93D60>: Failed to resolve '36' ([Errno 11001] getaddrinfo failed)"))