Ошибка: HTTPConnectionPool(host='38', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000202765422F0>: Failed to resolve '38' ([Errno 11001] getaddrinfo failed)"))