Ошибка: HTTPConnectionPool(host='bytefcdn-ttpeu.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002C395650880>: Failed to resolve 'bytefcdn-ttpeu.com' ([Errno 11001] getaddrinfo failed)"))