Ошибка: HTTPConnectionPool(host='digital.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000152721ADBD0>: Failed to resolve 'digital.com' ([Errno 11001] getaddrinfo failed)"))