Ошибка: HTTPConnectionPool(host='urldefense.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015272A56CE0>, 'Connection to urldefense.com timed out. (connect timeout=10)'))