Ошибка: HTTPConnectionPool(host='usgs.gov', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015270530460>, 'Connection to usgs.gov timed out. (connect timeout=10)'))